platform :osx, '10.10'
use_frameworks!

target 'Photo Management Studio' do
  pod 'Alamofire'
  pod 'CocoaAsyncSocket'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'INAppStoreWindow'
  pod 'ITProgressIndicator'
end

