use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'

target 'Photo Management Studio' do
    pod 'CocoaAsyncSocket'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftHTTP', '~> 1.0.4'
    pod 'ITProgressIndicator', '~>0.1'
end