namespace ExifProcessLib.Models
{
    public enum ExifCompression
    {
        Uncompressed                                            = 1,
        CCITT1D                                                 = 2,
        T4Group3Fax                                             = 3,
        T6Group4Fax                                             = 4,
        LZW                                                     = 5,
        JPEGOldStyle                                            = 6,
        JPEG                                                    = 7,
        AdobeDeflate                                            = 8,
        JBIGBW                                                  = 9,
        JBIGColor                                               = 10,
        JPEG2                                                   = 99,
        Kodak262                                                = 262,
	    Next                                                    = 32766,
	    SonyARWCompressed                                       = 32767,
	    PackedRAW                                               = 32769,
	    SamsungSRWCompressed                                    = 32770,
	    CCIRLEW                                                 = 32771,
	    SamsungSRWCompressed2                                   = 32772,
	    PackBits                                                = 32773,
	    Thunderscan                                             = 32809,
	    KodakKDCCompressed                                      = 32867,
	    IT8CTPAD                                                = 32895,
	    IT8LW                                                   = 32896,
	    IT8MP                                                   = 32897,
	    IT8BL                                                   = 32898,
	    PixarFilm                                               = 32908,
	    PixarLog                                                = 32909,
	    Deflate                                                 = 32946,
	    DCS                                                     = 32947,
	    JBIG                                                    = 34661,
	    SGILog                                                  = 34676,
	    SGILog24                                                = 34677,
	    JPEG2000                                                = 34712,
	    NikonNEFCompressed                                      = 34713,
	    JBIG2TIFFFX                                             = 34715,
	    MicrosoftDocumentImagingMDIBinaryLevelCodec             = 34718,
	    MicrosoftDocumentImagingMDIProgressiveTransformCodec    = 34719,
	    MicrosoftDocumentImagingMDIVector                       = 34720,
	    LossyJPEG                                               = 34892,
	    KodakDCRCompressed                                      = 65000,
	    PentaxPEFCompressed                                     = 65535
    }
}
